#Docker compose file to create mongo and mongo-express container with shared env variables
#Created by Aswin KS

version: '3'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: aswin     #Dont use plain text.this is for testing
    volumes:
      - mongo-db-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root 
      ME_CONFIG_MONGODB_ADMINPASSWORD: aswin  #Dont use plain text.this is for testing
    depends_on:
      - mongo
volumes:
  mongo-db-data: